// This file is auto-generated by Lovable. Do not modify it.

// import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
// import { supabase } from "../supabase/client";
// const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      return { error: new Error("OAuth is not available") };
    },
  },
};
