// This file is automatically generated. Do not edit it directly.
// Disabled Supabase temporarily due to build issues

export const supabase = {
  auth: {
    signUp: () => Promise.reject(new Error('Auth disabled')),
    signIn: () => Promise.reject(new Error('Auth disabled')),
    signOut: () => Promise.reject(new Error('Auth disabled')),
    getUser: () => Promise.reject(new Error('Auth disabled')),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
  },
};
